---
driver_plugin: vagrant

platforms:
- name: centos-6.4-i386
  driver_config:
    provider: virtualbox
    box: opscode_centos-6.4-i386
    require_chef_omnibus: true

suites:
- name: default
  run_list:
    - recipe[rails]
  attributes: {}